# Generated by Django 5.1 on 2025-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('validade', models.DateField(verbose_name='Data de Validade')),
            ],
        ),
    ]
